---
- hosts: nodes
# Install Packages V
# export tokens and to linux path permanantly V
# Clone Github V
# (Github ssh key is located in this cotrol machine) 
# Run Task Manager Bot
  vars:
    dest_dir: /home/ubuntu/dev
    gh_repo: git@github.ncsu.edu:yhu22/CSC510_F17_Project.git
    gh_branch: deploy
    packages:
      - git
      - python-pip
      - python-setuptools
      - git-core
      - python-setuptools
      - debconf-utils
    pippackages:
      - slackclient
      - py-trello
      - pyrebase
      - python-firebase

  tasks:
    # - name: Set Env
    #   shell: "echo $BOARD_NAME"
    #   environment:
    #      BOARD_NAME: "Demo Board"
    - name: Adding the path in the bashrc files
      lineinfile: 
        dest: /home/ubuntu/.bashrc 
        line: "export TEAM_NAME=510projectteam export BOARD_NAME='Demo Board' export BOT_TOKEN=xoxb-266498254006-btD2n1TcKdi5MY6AKlPGTwnm export BOT_ID=U7UEN7G06  export TRELLO_API_KEY=dbf6947f87a8dcb83f090731a27e8bd4 export TRELLO_API_SECRET=f57a6c66081742aa5f6149d329c3581d53231c308e4cc9f78b31230ce13b3bb8 export TRELLO_TOKEN=414df911de9e839c8ab9838c8fa1723107fba5848e5049269d88e5e94a348f31 export FIREBASE_API_KEY=AIzaSyCC5OzyEqGBcGZkpyUP90qUnyCCJY8SRQ8 export FIREBASE_AUTH_DOMAIN=taskmangerbot.firebaseapp.com export FIREBASE_DATABASE_URL=https://taskmangerbot.firebaseio.com export FIREBASE_STORAGE_BUCKET=taskmangerbot.appspot.com export GMAIL_ID=bot510project@gmail.com export GMAIL_PASS=simtiaz1234"
        insertafter: 'EOF' 
        state: present
    - shell: . /home/ubuntu/.bashrc && echo $TEAM_NAME
      args:
        executable: /bin/bash
      register: myvar
    - debug: var=myvar.stdout
    
    - name: Copy setting.sh File for sourcing
      copy:
        src: /home/ubuntu/setting.sh
        dest: /home/ubuntu/setting.sh

    - name: Source the .bashrc file
      command: bash -lc "source .bashrc"
      become: yes
    - name: Print env var
      command: bash -lc "printenv > env.out"
    # - name: Clean files
    #   command: bash -lc "rm setting.sh"
    #   become: yes

    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: yes
      with_items: "{{packages}}"
      become: yes
    - debug:
        msg: "{{ item }}"
      with_items: "{{packages}}"

    - name: PIP install python packages
      pip:
        name: "{{ item }}"
      with_items: "{{pippackages}}"
      become: yes

    - name: Copy ssh public key from server to client
      copy:
        src: /home/ubuntu/.ssh/id_rsa.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub

    - name: Copy ssh private key from server to client
      copy:
        src: /home/ubuntu/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa

    - name: SSH Clone Github Repo
      git: repo={{ gh_repo }}
           version={{ gh_branch }}
           dest={{ dest_dir }}
           accept_hostkey=yes
           key_file="/home/ubuntu/.ssh/id_rsa"
      become: yes
    - name: Run Task Manager Bot
      command: bash -lc "python dev/src/main.py"
      become: yes
