---
- hosts: nodes
# Install Packages V
# export tokens and to linux path permanantly V
# Clone Github V
# (Github ssh key is located in this cotrol machine) V
# Run Task Manager Bot V
  environment:
     TEAM_NAME: 510projectteam
     BOARD_NAME: 'Demo Board'
     BOT_TOKEN: xoxb-266498254006-nLVi9gotROgDosCDowr6eGut
     BOT_ID: U7UEN7G06 
     TRELLO_API_KEY: dbf6947f87a8dcb83f090731a27e8bd4
     TRELLO_API_SECRET: f57a6c66081742aa5f6149d329c3581d53231c308e4cc9f78b31230ce13b3bb8
     TRELLO_TOKEN: 414df911de9e839c8ab9838c8fa1723107fba5848e5049269d88e5e94a348f31
     FIREBASE_API_KEY: AIzaSyCC5OzyEqGBcGZkpyUP90qUnyCCJY8SRQ8
     FIREBASE_AUTH_DOMAIN: taskmangerbot.firebaseapp.com
     FIREBASE_DATABASE_URL: https://taskmangerbot.firebaseio.com
     FIREBASE_STORAGE_BUCKET: taskmangerbot.appspot.com
     GMAIL_ID: bot510project@gmail.com
     GMAIL_PASS: simtiaz1234
  vars:
    dest_dir: /home/ubuntu/dev
    gh_repo: git@github.ncsu.edu:yhu22/CSC510_F17_Project.git
    gh_branch: master
    envVars:
        - TEAM_NAME
        - BOARD_NAME
        - BOT_TOKEN
        - BOT_ID
        - TRELLO_API_KEY
        - TRELLO_API_SECRET
        - TRELLO_TOKEN
        - FIREBASE_API_KEY
        - FIREBASE_AUTH_DOMAIN
        - FIREBASE_DATABASE_URL
        - FIREBASE_STORAGE_BUCKET
        - GMAIL_ID
        - GMAIL_PASS
    packages:
      - git
      - npm
      - nodejs
      - python-pip
      - python-setuptools
      - git-core
      - python-setuptools
      - debconf-utils
    pippackages:
      - slackclient
      - py-trello
      - pyrebase
      - python-firebase

  tasks:
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: yes
      with_items: "{{packages}}"
      become: yes
    - debug:
        msg: "{{ item }}"
      with_items: "{{packages}}"
    - name: PIP install python packages
      pip:
        name: "{{ item }}"
      with_items: "{{pippackages}}"
      become: yes

    - name: Copy ssh public key from server to client
      copy:
        src: /home/ubuntu/.ssh/id_rsa.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub

    - name: Copy ssh private key from server to client
      copy:
        src: /home/ubuntu/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa

    - name: SSH Clone Github Repo
      git: repo={{ gh_repo }}
           version={{ gh_branch }}
           dest={{ dest_dir }}
           accept_hostkey=yes
           key_file="/home/ubuntu/.ssh/id_rsa"
      become: yes
    - name: Test Env
      command: python -c "import os; print os.environ.get('{{ item }}')"
      #command: python -c "import os; print os.environ.get('{{ item }}')" > envTest.out
      with_items: envVars
      register: output
    - debug: var=item.stdout
      with_items: output.results

    - name: verify npm is installed
      command: npm --version
      register: npm_v
    - debug: 
        msg: "npm version: {{ npm_v }}"
    - name: Create SymbolicLink for nodejs
      become: yes
      command: bash -lc "cd /home/ubuntu/dev/src && npm install && ln -s /usr/bin/nodejs /usr/bin/node"
    - name: Install forever
      npm: name=forever global=yes state=present
      become: yes

    - name: Run Task Manager Bot
      command: nohup forever -c python dev/src/main.py
      become: yes
      register: bot_output
    - debug: 
        msg: "{{ bot_output.stdout }}"
    - name: Clean up
      command: rm /usr/bin/node
      become: yes



